// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	api "github.com/go_workshop_1/internal/api"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetWeather provides a mock function with given fields:
func (_m *Client) GetWeather() (*api.WeatherResponse, error) {
	ret := _m.Called()

	var r0 *api.WeatherResponse
	if rf, ok := ret.Get(0).(func() *api.WeatherResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.WeatherResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
