name: CICD

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-go@v1
        with:
          go-version: 1.15

  deploy:
    name: Deploy on Heroku
    runs-on: ubuntu-latest
    # need for step lint and test to be successful
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku containter registry
        env:
          # get token from repo secrets
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web



